version: "3.8"

services:
  producer:
    image: producer
    container_name: producer
    ports:
      - "9090:8080"
    environment:
      SPRING_CONFIG_LOCATION: file:/config/
    volumes:
      - ./src/main/resources:/config
    networks:
      - producer-net

networks:
  producer-net:
    external: true
