apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-db-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: {{ .Values.database.username | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.database.password | quote }}
