version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:2.515-jdk21
    privileged: true
    user: root
    ports:
      - 8082:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /Users/bernabaris/IdeaProjects/github/story-nest/backend/docker/jenkins/jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock